### ISSUE TITLE
捕捉球丟原版生物會以上錯誤無法捉取 捕捉球消失

### ISSUE THREAD

**Issue by kirtar-tw** [NUTT1101/CatchBall#3]
[21:48:26 ERROR]: Could not pass event ProjectileHitEvent to CatchBall v1.1.1
java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/MythicMobs
        at com.pohuang.event.HitEvent.mmCheck(HitEvent.java:221) ~[CatchBall-1.1.1.jar:?]
        at com.pohuang.event.HitEvent.CatchBallHitEvent(HitEvent.java:87) ~[CatchBall-1.1.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor992.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-165]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1402) ~[paper-1.18.1.jar:git-Paper-165]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:169) ~[?:?]
        at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:79) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-165]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-165]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-165]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-165]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-165]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-165]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.MythicMobs
        ... 21 more

MythicMobs-5.0.3-SNAPSHOT
MythicLib-1.3.1
捕捉球丟原版生物會以上錯誤無法捉取 捕捉球消失

**Comment by NUTT1101** [comment]
錯誤原因：CatchBall 太久未升級 MythicMobs Api ，導致舊有Api新版本不在支援。

另外發現在MythicMobs 付費版以及免費版 兩個版本中， BukkitApiHelper此類別 package(檔案目錄)不相同，導致要請求 isMythicMobs()此方法找不到Class，最後利用反射將即時獲得 BukkitApiHelper package.

詳細程式碼請參照: [此處](https://github.com/NUTT1101/CatchBall/commit/1c9ebb504adbd11352249838e71135bab45192d5#diff-9615f406822eb2e4e02e96e83474781c86e8589edf8baf5f8804e59634c44ea4L222)
