### ISSUE TITLE
Unable to load, error

### ISSUE THREAD

**Issue by areny7** [NUTT1101/CatchBall#6]
The plugin cannot be loaded correctly in the 1.16 paper environment

[02:16:20] [Server thread/ERROR]: Could not load 'plugins\CatchBall-1.1.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/github/nutt1101/CatchBall has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by NUTT1101** [comment]
Thank you for your reporting!
I have fixed this bug on [v.1.1.5](https://github.com/NUTT1101/CatchBall/releases/tag/v.1.1.5).
---
**Description**
My compiled version of java is `java-17`,because Minecraft version `1.17~1.19` only supports `java-17` or above,but 1.16 only supports `java-16`,so when you use `java-16` to load this plugin, it crashes.
