### ISSUE TITLE
can't catch anything

### ISSUE THREAD

**Issue by AdminHcat** [NUTT1101/CatchBall#9]
[23:55:56 ERROR]: Could not pass event ProjectileHitEvent to CatchBall v1.1.6
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R2/entity/CraftEntity
        at com.github.nutt1101.NBT_v1_19.isCustomEntity(NBT_v1_19.java:34) ~[CatchBall-1.1.6.jar:?]
        at com.github.nutt1101.event.HitEvent.getIsCustomEntity(HitEvent.java:262) ~[CatchBall-1.1.6.jar:?]
        at com.github.nutt1101.event.HitEvent.CatchBallHitEvent(HitEvent.java:105) ~[CatchBall-1.1.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1920.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1974]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.tonimatasdev.perworldplugins.util.listener.PerWorldRegisteredListener.callEvent(PerWorldRegisteredListener.java:62) ~[PerWorldPlugins-1.3.6.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1974]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1974]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1481) ~[purpur-1.19.4.jar:git-Purpur-1974]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:202) ~[?:?]
        at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:69) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1293) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:755) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.19.4.jar:git-Purpur-1974]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:732) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1575) ~[purpur-1.19.4.jar:git-Purpur-1974]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1974]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1974]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1974]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1974]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_19_R2.entity.CraftEntity
        ... 24 more

**Comment by MagicTeaMC** [comment]
This plugin currently only supports 1.19.3, before the author updates this plugin, you can first use this fork I made :)  
https://github.com/milkteamc/CatchBall-fork/releases/

**Comment by NUTT1101** [comment]
Hello @AdminHcat, thank you for your report, a new release version: [here](https://github.com/NUTT1101/CatchBall/releases/tag/v1.1.7) . 👍 

@MagicTeaMC Thank you for your hotfix. 😃
